title: 'Mr. Hannes'
author: 'Hannes D''Hulster'
description: 'Hannes D''Hulster, User experience designer. Empathize, ideate, test.'
exclude: ['_site','scss','*scss','Gem*','Guard*','*rb','.sass-cache','.git*','config.rb','*.md','*.json','docroot','node_modules','gulpfile.js','install.sh','lint.yml']
